### ISSUE TITLE
Excel データを JSON に変換

### ISSUE THREAD

**Issue by ohyama** [stop-covid19-hyogo/covid19-scraping#1]
兵庫県のサイトにある Excel データを JSON に変換するスクリプトを作成してください。

新型コロナウイルスに感染した患者の状況
https://web.pref.hyogo.lg.jp/kk03/corona_kanjyajyokyo.html

新型コロナウイルス感染症の県内検査状況について
https://web.pref.hyogo.lg.jp/kf16/singatakoronakensa.html

**Comment by y-chan** [comment]
恐らく公開されている情報はすべて反映できるようになりました。
あとはGitHub Actionsを利用して自動化すればいいんですかね...?

**Comment by ohyama** [comment]
ありがとう、データが生成されているのでこちらの Issue はクローズしますね。
データが正しいかはサイトリリース前のテストで再確認します。

> あとはGitHub Actionsを利用して自動化すればいいんですかね...?

こちらも #2  で対応してくれてますね、ありがとう！
