### ISSUE TITLE
データ取得元の明示

### ISSUE THREAD

**Issue by roborovskii-info** [stop-covid19-hyogo/covid19-scraping#13]
## 改善詳細 / Details of Improvement
- データ取得元がソースコードを見ないと確認できないため、README.mdなどに追加しておいたほうがよいと思われます

**Comment by y-chan** [comment]
以下コミットにて追加しました。
一旦これにて対応完了としたいですが、ご意見等あればよろしくお願いします。
https://github.com/stop-covid19-hyogo/covid19-scraping/commit/3cf73c677ec042f71d867e175241f15111a7c0ab

**Comment by roborovskii-info** [comment]
いいと思います!
ご対応ありがとうございます

**Comment by y-chan** [comment]
解決ということでクローズします。
