### ISSUE TITLE
JSON データの日付フォーマットを統一する

### ISSUE THREAD

**Issue by ohyama** [stop-covid19-hyogo/covid19-scraping#17]
## 改善詳細 / Details of Improvement
JSON データの日付フォーマットがバラバラです。以下の形式に統一してください。

Code for Japan が策定する Covid19 のフォーマットに合わせ以下の形式に統一してください。

4/5 追記 
政府CIOポータルの仕様に準拠すると CfJ の仕様に追記がありました。
申し訳ないですが、日時は以下のフォーマットに合わせるようお願いします。

https://cio.go.jp/sites/default/files/uploads/documents/1015-1_gyousei_data_model_datetime.pdf

- 日付: `YYYY-MM-DD`
- 日時: `YYYY-MM-DDTHH:MM:SS+09:00`

## 関連 Issue

https://github.com/stop-covid19-hyogo/covid19/issues/52

**Comment by chanrute** [comment]
@ohyama 
issue立て、ありがとうございます。
つまり、 `2020-01-25T08:00:00.000Z`このような表記は`2020-01-25 08:00` にすべき、ということですね。これから少し対応してみます。

**Comment by ohyama** [comment]
> 2020-01-25T08:00:00.000Zこのような表記は2020-01-25 08:00 にすべき

はい、その通りでございます！

また、 `2020-03-01T00:00:00+09:00` のように、 0 時を表す項目は日付と扱い `YYYY-MM-DD` で統一をお願いいたします。

**Comment by ohyama** [comment]
政府CIOポータルの仕様に準拠すると CfJ の仕様に追記がありました。
申し訳ないですが、日時は以下のフォーマットに合わせるようお願いします。

https://cio.go.jp/sites/default/files/uploads/documents/1015-1_gyousei_data_model_datetime.pdf

- 日時: `YYYY-MM-DDTHH:MM:SS+09:00`

**Comment by y-chan** [comment]
last_updateを以下のコミットでisoformatに揃え、inspectionsの特殊な日付をYYYY-MM-DDに揃えたので、このissueはクローズします。
https://github.com/stop-covid19-hyogo/covid19-scraping/commit/86697976507b68a4a0801c5cbbabd011e0600ce4
