### ISSUE TITLE
JSON作成失敗時にエラーをslackに通知したい

### ISSUE THREAD

**Issue by imabari** [stop-covid19-hyogo/covid19-scraping#19]
## 改善詳細 / Details of Improvement
- JSON作成失敗時にエラーをslackに通知したい

## 期待する見せ方・挙動 / Expected behavior
- エラー発生時にslackに通知する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by rioil** [comment]
この子使えそうですね
https://github.com/homoluctus/slatify
