### ISSUE TITLE
GitHub Actions を使用して JSON の生成を自動化する

### ISSUE THREAD

**Issue by ohyama** [stop-covid19-hyogo/covid19-scraping#2]
GitHub Actions を使用してスクリプトを実行し、 JSON の生成を自動化してください。

Code for Sappro さんのコードが参考になります。
https://github.com/codeforsapporo/covid19hokkaido_scraping

**Comment by y-chan** [comment]
以下のコミットにて自動生成するようにしました。
https://github.com/stop-covid19-hyogo/covid19-scraping/commit/5a12ab96033a72bd1b245e9250cb260b8009fa9b

**Comment by ohyama** [comment]
ありがとう！ `gh-pages` ブランチにデータがあることを確認しました！
