### ISSUE TITLE
検査陽性者の状況を取得

### ISSUE THREAD

**Issue by shikibu9419** [stop-covid19-hyogo/covid19-scraping#4]
現在, 検査陽性者の状況は手動で取得しており, scrapingの際に自動で取得してくるようにする.

手順としては
- https://web.pref.hyogo.lg.jp/kk03/corona_hasseijyokyo.html よりPDFファイルを取得
- PDFファイルよりテキストを取得
- テキストを整形して `main_summary.json`として保存

PDFパーサにはPythonの`pdfminer.six`を用いる.
https://pdfminersix.readthedocs.io/en/latest/index.html

**Comment by ohyama** [comment]
データ形式どうなるか分かりませんが、やってみましょう！変更されても手作業でなんとかできるデータですしね！

ご対応よろしくお願いします！

**Comment by y-chan** [comment]
#5 をマージしたので、解決ということでこのissueはクローズします。
