### ISSUE TITLE
ダウンロードした Excel も gh-pages に保存する

### ISSUE THREAD

**Issue by ohyama** [stop-covid19-hyogo/covid19-scraping#6]
## 改善詳細 / Details of Improvement
- データ生成に使用した Excel も `ph-pages` ブランチに保存していただけませんか
- サイトの JSON データを更新する際、Excel と一致しているか念のため確認します

**Comment by y-chan** [comment]
こういう時の為にリファクタしておきました
https://github.com/stop-covid19-hyogo/covid19-scraping/commit/f783434ad6d74f76624893bc7de6b34533590034
このコミットでxlsxファイルの保存を有効化しました。
https://github.com/stop-covid19-hyogo/covid19-scraping/commit/6045ba6275592c13522bdb21e28bf8eb08fe2616

**Comment by ohyama** [comment]
おおー、ありがとう！流石です！

クローズします！

**Comment by ohyama** [comment]
Excel ちゃんとありますね！ありがとう！

https://github.com/stop-covid19-hyogo/covid19-scraping/tree/gh-pages
